baseURL = "https://www.rageshravi.com/"
languageCode = "en-us"
title = "RAGESHRAVI.COM"
theme = "rageshravi-theme"
copyright = "Copyright © 2019"
canonifyurls = true
paginate = 30
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
