# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "https://infallible-goodall-3a896c.netlify.com/*"
  to = "https://www.rageshravi.com/"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
